version: 2
jobs:
  build:
    docker:
    - image: buildpack-deps:trusty
    steps:
    - checkout
    - run:
        name: Install deps
        command: apt-get update && apt-get install -y git cmake zip
    - run:
        name: Get submodules
        command: git submodule update --init --recursive
    - run:
        name: Build
        command: mkdir build && cd build && cmake -DCMAKE_INSTALL_PREFIX=../sdk/ .. && make && make install && cd ..
    - run:
        name: Zip the SDK
        command: cd sdk && zip -r ../sdk.zip . && cd ..
    - store_artifacts:
        path: sdk.zip
        destination: mod_sdk.zip
    - store_artifacts:
        path: sdk/lib/libserver_modloader.so
        destination: libserver_modloader.so
  publish-github-release:
    docker:
    - image: cibuilds/github:0.10
    steps:
    - attach_workspace:
        at: ./artifacts
    - run:
        name: Publish GitHub release
        command: |
          ghr -t ${GITHUB_TOKEN} -u ${CIRCLE_PROJECT_USERNAME} -r ${CIRCLE_PROJECT_REPONAME} -c ${CIRCLE_SHA1} \
          -delete "Continous Build" ./artifacts/

workflows:
  version: 2
  main:
    jobs:
    - build
    - publish-github-release:
        requires:
          - build
