version: 2
jobs:
  build:
    docker:
    - image: buildpack-deps:trusty
    steps:
    - checkout
    - run:
        name: Install deps
        command: apt-get update && apt-get install -y git cmake zip
    - run:
        name: Get submodules
        command: git submodule update --init --recursive
    - run:
        name: Build
        command: mkdir build && cd build && cmake -DCMAKE_INSTALL_PREFIX=../sdk/ .. && make && make install && cd ..
    - run:
        name: Zip the SDK
        command: cd sdk && zip -r ../sdk.zip . && cd ..
    - store_artifacts:
        path: sdk.zip
    - store_artifacts:
        path: sdk/lib/libserver_modloader.so