version: 2
jobs:
  build:
    docker:
    - image: buildpack-deps:trusty
    steps:
    - checkout
    - run:
        name: Install deps
        command: apt-get update && apt-get install -y git cmake zip
    - run:
        name: Get submodules
        command: git submodule update --init --recursive
    - run:
        name: Build
        command: mkdir build && cd build && cmake -DCMAKE_INSTALL_PREFIX=../sdk/ .. && make && make install && cd ..
    - run:
        name: Pack the SDK and modloader
        command: |
          mkdir artifacts && cd sdk &&
          zip -r ../artifacts/mod_sdk.zip . && cp lib/libserver_modloader.so ../artifacts && cd ..
    - persist_to_workspace:
        root: artifacts/
        paths: "*"
    - store_artifacts:
        path: artifacts/
        destination: /
  publish-github-release:
    docker:
    - image: cibuilds/github:0.10
    steps:
    - attach_workspace:
        at: ./artifacts
    - run:
        name: Publish GitHub release
        command: |
          ghr -t ${GITHUB_TOKEN} -u ${CIRCLE_PROJECT_USERNAME} -r ${CIRCLE_PROJECT_REPONAME} -c ${CIRCLE_SHA1} \
          -delete ${CIRCLE_TAG} ./artifacts/

workflows:
  version: 2
  main:
    jobs:
    - build
    - publish-github-release:
        requires:
          - build
        filters:
          tags:
            only: /.*/
